baseURL = 'https://neviim.post-self.ink/'
languageCode = 'en-us'
title = "Nevi'im"
theme = 'maddybook'
paginatePath = ""
disablePathToLower = true

[permalinks]
    post = '/:filename/'

[params]
    author = 'Madison Scott-Clary'
    home = 'https://makyo.ink'
    copyright = 2022
    customCSS = ['/css/neviim.css']
    subtitle = 'Post-Self book III'
    subtitleLink = 'https://post-self.ink'

[markup.goldmark.renderer]
    unsafe = true
